In [2]:
import pandas as pd

df = pd.read_csv('data/raw/it_incident_log_dataset/incident_event_log.csv')
df.head()

,number,incident_state,active,reassignment_count,reopen_count,sys_mod_count,made_sla,caller_id,opened_by,opened_at,...,u_priority_confirmation,notify,problem_id,rfc,vendor,caused_by,closed_code,resolved_by,resolved_at,closed_at
0,INC0000045,New,True,0,0,0,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
1,INC0000045,Resolved,True,0,0,2,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
2,INC0000045,Resolved,True,0,0,3,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
3,INC0000045,Closed,False,0,0,4,True,Caller 2403,Opened by 8,29/2/2016 01:16,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 149,29/2/2016 11:29,5/3/2016 12:00
4,INC0000047,New,True,0,0,0,True,Caller 2403,Opened by 397,29/2/2016 04:40,...,False,Do Not Notify,?,?,?,?,code 5,Resolved by 81,1/3/2016 09:52,6/3/2016 10:00

In [15]:
sample_20 = df.sample(int(df.shape[0] / 10))
sample_20.to_csv('amostra.csv')

In [14]:
int(df.shape[0] / 10)

14171

(141712, 36)

In [1]:
import pandas as pd

df = pd.read_csv('data/raw/rba-dataset.csv')
df.head()

,index,Login Timestamp,User ID,Round-Trip Time [ms],IP Address,Country,Region,City,ASN,User Agent String,Browser Name and Version,OS Name and Version,Device Type,Login Successful,Is Attack IP,Is Account Takeover
0,0,2020-02-03 12:43:30.772,-4324475583306591935,NaN,10.0.65.171,NO,-,-,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like ...,Firefox 20.0.0.1618,iOS 13.4,mobile,False,False,False
1,1,2020-02-03 12:43:43.549,-4324475583306591935,NaN,194.87.207.6,AU,-,-,60117,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile 46.0.2490,Android 4.1,mobile,False,False,False
2,2,2020-02-03 12:43:55.873,-3284137479262433373,NaN,81.167.144.58,NO,Vestland,Urangsvag,29695,Mozilla/5.0 (iPad; CPU OS 7_1 like Mac OS X) ...,Android 2.3.3.2672,iOS 7.1,mobile,True,False,False
3,3,2020-02-03 12:43:56.180,-4324475583306591935,NaN,170.39.78.152,US,-,-,393398,Mozilla/5.0 (Linux; Android 4.1; Galaxy Nexus...,Chrome Mobile WebView 85.0.4183,Android 4.1,mobile,False,False,False
4,4,2020-02-03 12:43:59.396,-4618854071942621186,NaN,10.0.0.47,US,Virginia,Ashburn,398986,Mozilla/5.0 (Linux; U; Android 2.2) Build/NMA...,Chrome Mobile WebView 85.0.4183,Android 2.2,mobile,False,True,False

In [2]:
df = df.drop(columns=['Is Attack IP', 'Is Account Takeover'])
rba_sample_10= df.sample(frac=0.001)
rba_sample_10.shape

(31269, 14)

In [3]:
rba_sample_10= df.sample(frac=0.001)
rba_sample_10.shape

(31269, 14)

In [4]:
rba_sample_10.to_csv('rba_sample_001.csv', index=True)

In [3]:
rba_sample_10.head()

,index,Login Timestamp,User ID,Round-Trip Time [ms],IP Address,Country,Region,City,ASN,User Agent String,Browser Name and Version,OS Name and Version,Device Type,Login Successful
1433372,1433372,2020-02-22 10:44:04.527,-3197055378497531009,NaN,176.107.128.167,PL,Mazovia,Warsaw,205727,Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 lik...,Chrome Mobile WebView 85.0.4183,iOS 11.2.6,mobile,True
17482036,17482036,2020-10-03 12:39:16.494,-8941203656012083405,NaN,141.0.82.6,NO,Rogaland,Stavanger,29695,Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like...,Android 2.3.3.2639,iOS 9.3.3,mobile,True
19379012,19379012,2020-10-29 06:14:06.373,-1895058636991954213,NaN,92.220.130.169,NO,Vestland,Stord,29695,'Mozilla/5.0 (X11; CrOS x86_64 13421.73.0) Ap...,Chrome 67.0.3396,Chrome OS 13421.73.0,desktop,True
16671757,16671757,2020-09-22 09:12:00.568,8079542460053629866,NaN,10.1.28.228,NO,-,-,34989,Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X...,Chrome Mobile WebView 87.0.4280.2259,iOS 6.1.3,tablet,True
18807999,18807999,2020-10-21 10:01:29.029,-6876694846771203187,NaN,46.249.251.25,NO,Trøndelag,Stjordal,49455,Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_1 like...,Chrome Mobile iOS 71.0.3578,iOS 10.0.1,mobile,False