In [11]:
import pandas as pd

attack_original = '/workspace/data/raw/Adema/attack_original.csv'
tram_original = '/workspace/data/raw/Adema/tram_original.json'
tram_with_all_labels = '/workspace/data/raw/Adema/tram_with_all_labels.csv'
tram_original_with_labels = '/workspace/data/raw/Adema/tram_original_with_labels.json'
tram_original ='/workspace/data/raw/Adema/tram_original.json'


#df_tram_original = pd.read_json(tram_original)
#df_tram_original_with_labels = pd.read_json(tram_original_with_labels)
#df_
tram_original = pd.read_json(tram_original)

In [16]:
df_attack_original = pd.read_csv(attack_original)
print(df_attack_original.shape)
df_attack_original.head()

(24399, 3)

                                                text  tactic technique
0  Adversaries may execute active reconnaissance ...  TA0043     T1595
1  Active scans are those where the adversary pro...  TA0043     T1595
2  Adversaries may perform different forms of act...  TA0043     T1595
3  These scans can also be performed in various w...  TA0043     T1595
4  Information from these scans may reveal opport...  TA0043     T1595

In [19]:
df_attack_original.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24399 entries, 0 to 24398
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       24399 non-null  object
 1   tactic     24399 non-null  object
 2   technique  24399 non-null  object
dtypes: object(3)
memory usage: 572.0+ KB

In [20]:
df_tram_with_all_labels = pd.read_csv(tram_with_all_labels)
print(df_tram_with_all_labels.shape)
df_tram_with_all_labels.head()

(9044, 591)

,text,TA0043,TA0042,TA0001,TA0002,TA0003,TA0004,TA0005,TA0006,TA0007,...,T1553.006,T1590.001,T1114.003,T1110.003,T1098.003,T1134.001,T1052.001,T1557.003,T1486,T1596.001
0,"From these reports, we know that the group use...",0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"We believe this access was abused, for example...",0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,What does the resulting watering hole look lik...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,This targeting of third party organizations to...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Online news outlets and general websites were ...,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0